### ISSUE TITLE
GPU used for fine tuning Wav2Vec model

### ISSUE THREAD

**Issue by jcsilva** [Edresson/Wav2Vec-Wrapper#4]
Hi,

I tried to follow all instructions published at Wav2Vec-Wrapper/Papers/SE&R-Challenge/README.md, but I had some problems using my GPU. Maybe you could give me some advices.

The hardware I have at home has only 4GB of memory and when try to run the train.py script, it always return this error message:

_RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 3.95 GiB total capacity; 3.23 GiB already allocated; 3.50 MiB free; 3.24 GiB res
erved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memo
ry Management and PYTORCH_CUDA_ALLOC_CONF_

I have already tried to:
1) shut down all processes that may use GPU memory (e.g. Xorg).
2) use a smaller batch size. I've tried 4, 2 and 1. No success.
3) use only small audio clips. I've selected one specific audio clip which size was more or less 500ms and repeated this unique sample 10 times im my training csv file. I know it wouldn't be a good strategy for training, but at this moment I just want to run a fine tuning round. Unfortunately I got the same error.

I'm sure the model can be loaded in my GPU because I'm able to run the inference script. When I did it, I saw that GPU memory usage by python3 was 2823MB and the inference step executed correctly.

So, if possible, could you give me any hints?

**Comment by lucasgris** [comment]
Hi @jcsilva , I guess the GPU usage during inference is lower than the GPU usage during training. So, I think you won't be able to finetune the Wav2vec LARGE model with only 4GB of memory, even if you could, the model probably would not learn very well. I would recommend at least 8 GB to start training with 5 to 10 seconds length audios.

If you don't have another GPU available, you could finetune the Wav2vec BASE model, it has approximately half the size of the LARGE one, or use a smaller model, like [Wav2vec-SEW](https://huggingface.co/asapp/sew-tiny-100k). Another option is to use 8kHz audios instead of 16kHz (but the model could lose some performance).

If you want to finetune the BASE model, you could use the pretrained models from VoxPopuli:
https://github.com/facebookresearch/voxpopuli
https://huggingface.co/facebook/wav2vec2-base-100k-voxpopuli
https://huggingface.co/facebook/wav2vec2-base-10k-voxpopuli

I recommend the 10k version, it seems to better generalize for Brazilian Portuguese:
https://huggingface.co/lgris/bp500-base100k_voxpopuli
https://huggingface.co/lgris/bp500-base10k_voxpopuli

Additional read:
https://discuss.huggingface.co/t/wav2vec2-0-memory-issue/4868

**Comment by jcsilva** [comment]
Thank you very much for your quick reply!
I think I'm gonna try to fine tune this BASE model and evaluate the
results.

Once again, thank you so much for your help.

Le mar. 14 déc. 2021 à 18:57, Lucas Gris ***@***.***> a
écrit :
